version: '3.9'

services:
  users_db:
    image: postgres:latest
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  tasks_db:
    image: postgres:latest
    container_name: tasks_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - "5433:5433"
    volumes:
      - tasks_data:/var/lib/postgresql/data

  information_db:
    image: postgres:latest
    container_name: information_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: information_db
    ports:
      - "5434:5434"
    volumes:
      - info_data:/var/lib/postgresql/data

volumes:
  auth_data:
  tasks_data:
  info_data:
  admin_data:
